---
- name: Retrieve existing underlay pool
  cisco.dnac.reserve_ip_subpool_info:
    dnac_host: "{{ dnac_host }}"
    dnac_verify: "{{ dnac_verify }}"
    siteId: "{{ fabric_site_id }}"
  register: site_pools

- name: Set default found pool state to false
  ansible.builtin.set_fact:
    underlay_pool_present: False

- name: Check for existing underlay pool
  ansible.builtin.set_fact:
    underlay_pool_present: True
    underlay_pool_id: "{{ item.id }}"
  with_items: 
    - "{{ site_pools.dnac_response.response }}"
  when: item.groupName == underlay_pool_name
  loop_control:
    label: "Found pool {{ item.groupName }}"

- name: Print found underlay state
  ansible.builtin.debug:
    var: underlay_pool_present
    
- name: Pause for input
  ansible.builtin.pause:
    prompt: "Continue to reserve the underlay IP pool?"
  when: not underlay_pool_present

- name: Reserve underlay pool
  cisco.dnac.reserve_ip_subpool_create:
    dnac_host: "{{ dnac_host }}"
    dnac_verify: "{{ dnac_verify }}"
    siteId: "{{ fabric_site_id }}"
    name: "{{ underlay_pool_name }}"
    type: "LAN"
    ipv4GlobalPool: "{{ global_pool_name | replace('X',pod) }}"
    ipv4Prefix: true
    ipv4Subnet: "{{ underlay_subnet | replace('X',pod) }}"
    ipv4PrefixLength: "{{ underlay_prefix_length }}"
    ipv4GateWay: "{{ underlay_gateway | replace('X',pod) }}"
  when: not underlay_pool_present

- name: Pause for input
  ansible.builtin.pause:
    prompt: "Continue to assign credentials to fabric site"

- name: Retrieve CLI credential ID
  cisco.dnac.global_credential_info:
    dnac_host: "{{ dnac_host }}"
    dnac_verify: "{{ dnac_verify }}"
    credentialSubType: "CLI"
  register: cred_cli_json

- name: Retrieve SNMP RO credential ID
  cisco.dnac.global_credential_info:
    dnac_host: "{{ dnac_host }}"
    dnac_verify: "{{ dnac_verify }}"
    credentialSubType: "SNMPV2_READ_COMMUNITY"
  register: cred_snmp_ro_json

- name: Retrieve SNMP RW credential ID
  cisco.dnac.global_credential_info:
    dnac_host: "{{ dnac_host }}"
    dnac_verify: "{{ dnac_verify }}"
    credentialSubType: "SNMPV2_WRITE_COMMUNITY"
  register: cred_snmp_rw_json

- name: Define credentials ID
  ansible.builtin.set_fact:
    cred_cli_id: "{{ cred_cli_json.dnac_response.response[0].id }}"
    cred_snmp_ro_id: "{{ cred_snmp_ro_json.dnac_response.response[0].id }}"
    cred_snmp_rw_id: "{{ cred_snmp_rw_json.dnac_response.response[0].id }}"

- name: Display credentials ID
  ansible.builtin.debug:
    msg: 
    - "CLI ID: {{ cred_cli_id}}"
    - "SNMP RO ID: {{ cred_snmp_ro_id }}"
    - "SNMP RW ID: {{ cred_snmp_rw_id }}"

- name: Assign credentials to fabric site
  cisco.dnac.site_assign_credential:
    dnac_host: "{{ dnac_host }}"
    dnac_verify: "{{ dnac_verify }}"
    siteId: "{{ fabric_site_id }}"
    cliId: "{{ cred_cli_id }}"
    snmpV2ReadId: "{{ cred_snmp_ro_id }}"
    snmpV2WriteId: "{{ cred_snmp_rw_id }}"
