---
- name: Check DNAC state
  hosts: podX_dnac
  gather_facts: no
  tasks:
  - name: Get devices info
    cisco.dnac.network_device_info:
      dnac_host: "{{dnac_host}}"
      dnac_verify: "{{dnac_verify}}"
    register: out_network

  - name: Display devices
    debug:
      msg: "Hostname: {{item.hostname}}, IP: {{item.managementIpAddress}}, Location: {{item.location}}"
    with_items:
      - "{{out_network.dnac_response.response}}"

