---
- name: Check LAN Automation sessions
  cisco.dnac.lan_automation_status_info:
    dnac_host: "{{ dnac_host }}"
    dnac_verify: "{{ dnac_verify }}"
  register: lan_auto_out

- name: Print LAN Automation sessions
  ansible.builtin.debug:
    msg: "{{ lan_auto_out.dnac_response.response if lan_auto_out.dnac_response.response | length > 0 else 'There are no previous LAN Automation sessions' }}"

- name: Retrieve latest LAN Auto session status data, only if it was running before
  ansible.builtin.set_fact:
    lan_auto_action: "{{ lan_auto_out.dnac_response.response[0].action }}"
    lan_auto_creation_time: "{{ lan_auto_out.dnac_response.response[0].creationTime }}"
    lan_auto_discovered_device_list: "{{ lan_auto_out.dnac_response.response[0].discoveredDeviceList }}"
    lan_auto_status: "{{ lan_auto_out.dnac_response.response[0].status }}"
  when: lan_auto_out.dnac_response.response | length > 0

- name: Display current LAN Auto status only if it was running before
  ansible.builtin.debug:
    msg:
      - "{{ lan_auto_action }}"
      - "{{ lan_auto_creation_time }}"
      - "{{ lan_auto_discovered_device_list }}"
      - "{{ lan_auto_status }}"
  when: lan_auto_out.dnac_response.response | length > 0

- name: Check if LAN Auto is running currently
  ansible.builtin.set_fact:
    lan_auto_is_running: >-
      {{ true if lan_auto_action is defined
      and (('start' in lan_auto_action | lower) or (('stop' in lan_auto_action | lower)
      and ('completed' not in lan_auto_status | lower)))
      else false }}

- name: Display LAN Auto running message
  ansible.builtin.debug:
    msg: "LAN Automation is currently running, the status is {{ lan_auto_status }}, aborting."
  when: lan_auto_is_running

- name: Abort if LAN Auto is currently running
  ansible.builtin.meta: end_play
  when: lan_auto_is_running

- name: Create LAN Automation session
  cisco.dnac.lan_automation:
    dnac_host: "{{ dnac_host }}"
    dnac_verify: "{{ dnac_verify }}"
    payload:
      - discoveredDeviceSiteNameHierarchy: "{{ site_name }}"
        multicastEnabled: true
        isisDomainPwd: "{{ isis_password }}"
        primaryDeviceManagmentIPAddress: "{{ seed_switch | replace('X', pod) }}"
        primaryDeviceInterfaceNames: "{{ seed_interfaces }}"
        ipPools:
          - ipPoolName: "{{ underlay_pool_name }}"
            ipPoolRole: "MAIN_POOL"
        discoveryDevices:
          - deviceHostName: "POD{{ pod }}_SW1"
            deviceManagementIPAddress: "10.1{{ pod }}.127.1"
            deviceSerialNumber: "{{ day0_switches.sw1_serial }}"
            deviceSiteNameHierarchy: "{{ site_name }}"
          - deviceHostName: "POD{{ pod }}_SW2"
            deviceManagementIPAddress: "10.1{{ pod }}.127.2"
            deviceSerialNumber: "{{ day0_switches.sw2_serial }}"
            deviceSiteNameHierarchy: "{{ site_name }}"

- name: Wait 20s to retrieve the status
  ansible.builtin.pause:
    seconds: 20

- name: Check LAN Auto status
  cisco.dnac.lan_automation_status_info:
    dnac_host: "{{ dnac_host }}"
    dnac_verify: "{{ dnac_verify }}"
  register: lan_auto_out

- name: Retrieve last status data
  ansible.builtin.set_fact:
    lan_auto_action: "{{ lan_auto_out.dnac_response.response[0].action }}"
    lan_auto_creation_time: "{{ lan_auto_out.dnac_response.response[0].creationTime }}"
    lan_auto_discovered_device_list: "{{ lan_auto_out.dnac_response.response[0].discoveredDeviceList }}"
    lan_auto_status: "{{ lan_auto_out.dnac_response.response[0].status }}"

- name: Display current LAN Auto status
  ansible.builtin.debug:
    msg:
      - "{{ lan_auto_action }}"
      - "{{ lan_auto_creation_time }}"
      - "{{ lan_auto_discovered_device_list }}"
      - "{{ lan_auto_status }}"
