- name: Provision Fabric Devices
  hosts: pod5_dnac
  connection: local
  gather_facts: false
  vars:
    - site_name: "global/Poland/Warszawa/Hector"
    - pod: X
    - underlay_pool_name: "UNDERLAY"
    - global_pool_name: "10.1X.64.0/18"
    - underlay_subnet: "10.1X.64.0"
    - underlay_prefix_length: "20"
    - underlay_gateway: "10.1X.64.1"
    - isis_password: "sisko"
    - seed_switch: "10.1X.127.3"
    - seed_interfaces:
      - "GigabitEthernet1/0/1"
      - "GigabitEthernet1/0/2"
      - "GigabitEthernet1/0/3"
      - "GigabitEthernet1/0/4"   

  roles:
    - get_info
    - role: pause
      message: "display gathered information"
    - display_info
    - role: pause
      message: "set up LAN Automation"
    - lan_auto_prep
    - role: pause
      message: "start LAN Automation"
    - lan_auto_start
