variables:
  IMAGE_NAME_CATC_BUILD: $CI_REGISTRY_IMAGE/catc_build  
  IMAGE_NAME_CATC_TEST: $CI_REGISTRY_IMAGE/catc_test   
  IMAGE_TAG_CATC_BUILD: "1.0"
  IMAGE_TAG_CATC_TEST: "1.0"

stages:
  - build

build_image:
  stage: build
  tags:
    - shell
  script:
    - echo $CI_COMMIT_BRANCH
    - echo $CI_REGISTRY_IMAGE
    - echo $IMAGE_NAME_CATC_BUILD
    - docker build -t $IMAGE_NAME_CATC_BUILD:$IMAGE_TAG_CATC_BUILD Docker/catc_build/.
    - echo $IMAGE_NAME_CATC_TEST
    - docker build -t $IMAGE_NAME_CATC_TEST:$IMAGE_TAG_CATC_TEST Docker/catc_test/.

push_image:
  stage: build
  needs:
    - build_image
  tags:
    - shell
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker push $IMAGE_NAME_CATC_BUILD:$IMAGE_TAG_CATC_BUILD
    - docker push $IMAGE_NAME_CATC_TEST:$IMAGE_TAG_CATC_TEST
