variables:
  IMAGE_NAME_CATC_BUILD: $CI_REGISTRY_IMAGE/catc_build  
  IMAGE_NAME_CATC_TEST: $CI_REGISTRY_IMAGE/catc_test   
  IMAGE_TAG_CATC_BUILD: "1.1"
  IMAGE_TAG_CATC_TEST: "1.0"

workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE == "Update .gitlab-ci.yml file" || $CI_COMMIT_MESSAGE =~ "/#DONOTRUN/"
      when: never
    - when: always

# Here an object cache is created to store .terraform sub-folder contents
# between container runs. With that, Terraform initialization 
# and the providers and modules downloaded will be persistent between runs
# In this case the cache is stored locally in the runnner where
# the container was executed
.dependencies_cache:
  cache:
    key: TF_NETASCODE
    paths:
      - "TF_NETASCODE/.terraform"
    policy: pull

stages:
  - build
  - validate  
  - plan
  - apply

build_image:
  stage: build
  tags:
    - shell
  script:
    - echo $CI_COMMIT_BRANCH
    - echo $CI_REGISTRY_IMAGE
    - echo $IMAGE_NAME_CATC_BUILD
    - docker build -t $IMAGE_NAME_CATC_BUILD:$IMAGE_TAG_CATC_BUILD Docker/catc_build/.
    - echo $IMAGE_NAME_CATC_TEST
    - docker build -t $IMAGE_NAME_CATC_TEST:$IMAGE_TAG_CATC_TEST Docker/catc_test/.

push_image:
  stage: build
  needs:
    - build_image
  tags:
    - shell
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker push $IMAGE_NAME_CATC_BUILD:$IMAGE_TAG_CATC_BUILD
    - docker push $IMAGE_NAME_CATC_TEST:$IMAGE_TAG_CATC_TEST

# The nac_validate job in validate stage is used to check the NaC syntax
nac_validate:
  stage: validate
  # The Docker image is required, the tag selects the docker runner
  # and the Docker image name is also provided
  needs:
    - push_image
  tags:
    - docker
  image: $IMAGE_NAME_CATC_BUILD:$IMAGE_TAG_CATC_BUILD
  # Here the reference to the cache is used
  extends: .dependencies_cache
  cache:
    policy: pull-push
  # Before the main script starts a Terraform initialization is performed
  before_script:
    - echo $CI_PIPELINE_SOURCE
    - echo $CI_COMMIT_BRANCH
    - cd TF_NETASCODE
    - source /root/build/bin/activate
    - pwd
    - chmod +x .init.sh
    - ./.init.sh
    - terraform version    
  # The main script here just invokes terraform validate
  script:
    - terraform validate
    - yamllint ./data/
    - nac-validate ./data/
  # The job should only start when the pipeline trigger is push
  # and the branch where commit was performed matches the regex
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /^feature.*/

# The tf_validate job in validate stage is used to check the HCL syntax
tf_plan:
  stage: plan
  # The Docker image is required, the tag selects the docker runner
  # and the Docker image name is also provided
  needs:
    - push_image
  tags:
    - docker
  image: $IMAGE_NAME_CATC_BUILD:$IMAGE_TAG_CATC_BUILD
  # Here the reference to the cache is used
  extends: .dependencies_cache
  cache:
    policy: pull-push
  # Before the main script starts a Terraform initialization is performed
  # And the Terraform shell variables are set based on GitLab variables
  before_script:
    - echo $CI_PIPELINE_SOURCE
    - echo $CI_COMMIT_BRANCH
    - cd TF_NETASCODE
    - pwd
    - chmod +x .init.sh
    - ./.init.sh
    - export TF_VAR_catc_username=${CATC_USERNAME}
    - export TF_VAR_catc_password=${CATC_PASSWORD}
    - export TF_VAR_catc_url=${CATC_URL}
  # The main script here just invokes terraform plan
  script:
    - terraform plan -out ./output.tfplan
    - terraform show ./output.tfplan

  # Generate artifacts based on plan output file
  artifacts:
    paths:
      - "./TF_NETASCODE/output.tfplan"
    untracked: false
    when: on_success
    expire_in: 30 days

  # The job should only start when the pipeline trigger is push
  # and the branch where commit was performed matches the regex
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /^feature.*/


# The tf_apply job in apply stage is used to apply the changes
tf_apply:
  stage: apply
  # The Docker image is required, the tag selects the docker runner
  # and the Docker image name is also provided
  tags:
    - docker
  image: $IMAGE_NAME_CATC_BUILD:$IMAGE_TAG_CATC_BUILD
  # Here the reference to the cache is used
  extends: .dependencies_cache
  cache:
    policy: pull-push
  # Before the main script starts a Terraform initialization is performed
  # And the Terraform shell variables are set based on GitLab variables
  before_script:
    - echo $CI_PIPELINE_SOURCE
    - echo $CI_COMMIT_BRANCH
    - cd TF_NETASCODE
    - pwd
    - chmod +x .init.sh
    - ./.init.sh
    - export TF_VAR_catc_username=${CATC_USERNAME}
    - export TF_VAR_catc_password=${CATC_PASSWORD}
    - export TF_VAR_catc_url=${CATC_URL}
  # The main script here just invokes terraform plan
  # Save output to the file and then display
  script:
    - terraform apply -auto-approve | tee ./output.tfapply

  # Generate artifacts based on apply output
  artifacts:
    paths:
      - "./TF_NETASCODE/output.tfapply"
    untracked: false
    when: on_success
    expire_in: 30 days
  # The job should only start when the pipeline trigger is push
  # and the branch where commit was performed matches the regex
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /^feature.*/
      when: manual
