- name: Provision Fabric Devices
  hosts: podX_dnac
  connection: local
  gather_facts: false
  vars:
    - site_name: "global/Poland/Warszawa/Hector"
  roles:
    - get_info
    - role: pause
      message: "display gathered information"
    - display_info
